spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
          #- RewritePath=/api/(?<segment>.*),/$\{segment}
          - SwaggerHeaderFilter
          - StripPrefix=1

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment}
            - SwaggerHeaderFilter
            - StripPrefix=1

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment}
            - SwaggerHeaderFilter
            - StripPrefix=1

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/api/order/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment}
            - SwaggerHeaderFilter
            - StripPrefix=1

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment}
            - SwaggerHeaderFilter
            - StripPrefix=1

        - id: three_route
          uri: lb://mall-three
          predicates:
            - Path=/api/three/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment}
            - SwaggerHeaderFilter
            - StripPrefix=1